<a href="https://colab.research.google.com/github/Ananthalakshmi-sm/NUMPY_ASSIGNMENT/blob/main/NUMPY_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Beginner

In [ ]:
#1.How do you import the NumPy library using an alias?
import numpy as np

In [ ]:
#2.How do you check the version and configuration of NumPy?
import numpy as np
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [ ]:
#3.How do you create a vector filled with zeros of size 10?
import numpy as np
vector=np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4.How do you find help/documentation for a NumPy function from the command line?
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [ ]:
#5.How do you create a zero vector of size 10 with the fifth element as 1?
import numpy as np
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#6.How do you create a vector with values from 10 to 49?
import numpy as np
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#7.How do you reverse a vector?
import numpy as np
vector=np.arange(10)
vector=vector[::-1]
print(vector)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#8.How do you create a 3x3 matrix with values from 0 to 8?
import numpy as np
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#9.How do you find indices of non-zero elements in an array?
import numpy as np
array=np.array([1,0,2,0,3,0])
indices=np.nonzero(array)
print(indices)

(array([0, 2, 4]),)


In [ ]:
#10.How do you create a 3x3 identity matrix?
import numpy as np
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#11.How do you generate a 3x3x3 array with random values?
import numpy as np
arr=np.random.random((3,3,3))
print(arr)

[[[0.91174116 0.44426075 0.88795893]
  [0.38663122 0.42892991 0.27142402]
  [0.7731192  0.09877267 0.58176307]]

 [[0.71761485 0.53702623 0.76980731]
  [0.11008409 0.37206168 0.57114669]
  [0.6828292  0.62904474 0.83536532]]

 [[0.96656571 0.66075439 0.09020114]
  [0.38726837 0.61212528 0.74095005]
  [0.80928451 0.17457812 0.04522511]]]


In [ ]:
#12.How do you find the min and max values in a 10x10 random matrix?
import numpy as np
matrix=np.random.random((10,10))
print("max value",matrix.max())
print("min value",matrix.min())

max value 0.9916784488276601
min value 0.04025483093007409


In [ ]:
#13.How do you calculate the mean of a random vector of size 30?
import numpy as np
vector=np.random.random(30)
mean=vector.mean()
print("mean",mean)

mean 0.4564709839528212


In [ ]:
#14.How do you create a 2D array with 1s on the border and 0s inside?
import numpy as np
array=np.ones((5,5))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#15.What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.?
import numpy as np
print(0*np.nan)
print(np.nan==np.nan)
print(np.nan!=np.nan)
print(np.isnan(np.nan))


nan
False
True
True


In [ ]:
#16.How do you create a matrix with values below the diagonal?
import numpy as np
matrix=np.tril(np.ones((3,3)))
print(matrix)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [ ]:
#17.How do you create a checkerboard pattern in an 8x8 matrix?
import numpy as np
checkerboard=np.zeros((8,8),dtype=int)
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#18.How do you find the index of a flat element in a 3D shape?
import numpy as np
arr = np.arange(27).reshape(3, 3, 3)
flat_index = 19
index_3d = np.unravel_index(flat_index, arr.shape)
print(index_3d)

(np.int64(2), np.int64(0), np.int64(1))


In [ ]:
#19.How do you create a checkerboard pattern using NumPy's tile function?
import numpy as np
checkerboard=np.tile([[0,1],[1,0]],(4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#20.How do you normalize a matrix (values between 0 and 1)?
import numpy as np
matrix = np.random.randint(1, 100, (3, 3))
normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print("Original:\n", matrix)
print("Normalized:\n", normalized)

Original:
 [[80 69 19]
 [46 90 13]
 [34 53 54]]
Normalized:
 [[0.87012987 0.72727273 0.07792208]
 [0.42857143 1.         0.        ]
 [0.27272727 0.51948052 0.53246753]]


In [ ]:
#21. How do you define a custom data type for storing color (RGBA)?
import numpy as np
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=color_dtype)
print(colors)
print(colors['r'])

[(255,   0, 0, 255) (  0, 255, 0, 255)]
[255   0]


In [ ]:
#22.How do you perform a matrix multiplication between two matrices?
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
result=A@B
print(result)

[[19 22]
 [43 50]]


In [ ]:
#23.How do you negate values between two given numbers in a vector?
import numpy as np
x=np.arange(10)
print("orginal:",x)
lower,upper=3,7
x[(x<=upper)&(x>=lower)]*=-1
print("Modified",x)

orginal: [0 1 2 3 4 5 6 7 8 9]
Modified [ 0  1  2 -3 -4 -5 -6 -7  8  9]


In [ ]:
#24.What is the output of sum(range(5), -1) vs np.sum(range(5), -1)?
import numpy as np
np.sum(range(5),-1)

np.int64(10)

Beginner

In [ ]:
#26.What happens when you divide integers or floats by zero in NumPy?
import numpy as np
np.array([1,2,3],dtype=int)/0

/tmp/ipython-input-1992047954.py:3: RuntimeWarning: divide by zero encountered in divide
  np.array([1,2,3],dtype=int)/0


array([inf, inf, inf])

In [ ]:
import numpy as np
np.array([1.,2.,3.],dtype=float)/0

/tmp/ipython-input-216862626.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([1.,2.,3.],dtype=float)/0


array([inf, inf, inf])

In [ ]:
import numpy as np
np.array([1.,0.],dtype=float)/0

/tmp/ipython-input-1815010736.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([1.,0.],dtype=float)/0
/tmp/ipython-input-1815010736.py:2: RuntimeWarning: invalid value encountered in divide
  np.array([1.,0.],dtype=float)/0


array([inf, nan])

In [ ]:
#27.How do you round a float array away from zero?
import numpy as np
x=np.array([-1.2, -1.5, -2.7, 1.2, 1.5, 2.7])
y=np.copysign(np.ceil(np.abs(x)),x)
print(y)

[-2. -2. -3.  2.  2.  3.]


In [ ]:
#28.How do you extract the integer part of a float using multiple methods?
import numpy as np
x = np.array([1.2, 2.9, -3.7, -1.1])

In [ ]:
#Using np.floor()
np.floor(x)

array([ 1.,  2., -4., -2.])

In [ ]:
#Using np.trunc()
np.trunc(x)

array([ 1.,  2., -3., -1.])

In [ ]:
#Using np.fix()
np.fix(x)

array([ 1.,  2., -3., -1.])

In [ ]:
#Using astype(int)
x.astype(int)

array([ 1,  2, -3, -1])

In [ ]:
#Using np.ceil()
np.ceil(x)

array([ 2.,  3., -3., -1.])

In [ ]:
#29.How do you create a 5x5 matrix with row values ranging from 0 to 4?
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
#30.How do you use a generator to create a NumPy array?
import numpy as np
gen=(i*i for i in range(5))
arr=np.fromiter(gen,dtype=int)
print(arr)

[ 0  1  4  9 16]


In [ ]:
#31.How do you create an array with evenly spaced values between 0 and 1 (excluded)?
import numpy as np
array=np.linspace(0,1,num=10,endpoint=False)
print(array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
#32.How do you sort a random array?
rand_arr=np.random.rand(5)
print("original:",rand_arr)
sorted_arr=np.sort(rand_arr)
print("sorted_arr:",sorted_arr)

original: [0.6742194  0.30362575 0.74551238 0.39372184 0.31426633]
sorted_arr: [0.30362575 0.31426633 0.39372184 0.6742194  0.74551238]


In [ ]:
#33.How do you sum an array faster than using np.sum?
import numpy as np
arr=np.random.rand(10000)
total=arr.sum()
print(total)

5023.498105936873


In [ ]:
#34.How do you check if two arrays are equal?
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array([1,2,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

True
False


In [ ]:
#35.How do you make a NumPy array read-only? Intermediate
import numpy as np
arr=np.array([1,2,3,4,5])
arr.flags.writeable=False
try:
    arr[0] = 10
except ValueError as e:
    print(e)

assignment destination is read-only


In [ ]:
#36.How do you convert Cartesian coordinates to polar coordinates?
import numpy as np
x=3
y=4
r=np.sqrt(x**2+y**2)
theta = np.arctan2(y, x)
print("Radius:", r)
print("Angle (radians):", theta)

Radius: 5.0
Angle (radians): 0.9272952180016122


In [ ]:
#37.How do you replace the maximum value in an array with zero?
arr = np.array([1, 3, 7, 2, 5])
max_index = np.argmax(arr)
arr[max_index] = 0
print(arr)

[1 3 0 2 5]


In [ ]:
#38.How do you create a structured array for (x, y) coordinate pairs?
import numpy as np
dtype=[('x',float),('y',float)]
coords = np.array([(1, 2), (3, 4), (5, 6)], dtype=dtype)
print(coords)
print(coords['x'])
print(coords['y'])

[(1., 2.) (3., 4.) (5., 6.)]
[1. 3. 5.]
[2. 4. 6.]


In [ ]:
#39.How do you create a Cauchy matrix using two arrays?
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
C = 1 / (x[:, None] - y[None, :])
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [ ]:
#40.How do you find the range of values for each NumPy scalar type?
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15


In [ ]:
#41.How do you display all values in a large array?
import numpy as np
arr=np.arange(100)
np.set_printoptions(threshold=np.inf)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#42.How do you find the closest value to a given scalar in an array?
arr = np.array([1, 3, 5, 7, 9])
val = 6
idx = (np.abs(arr - val)).argmin()
closest = arr[idx]
print("Closest value to", val, "is", closest)


Closest value to 6 is 5


In [ ]:
#43.How do you create a structured array with position and color fields?
import numpy as np
dtype = [('position', float, 2), ('color', 'U10')]
data = np.array([((1.0, 2.0), 'red'),
                 ((3.0, 4.0), 'blue'),
                 ((5.0, 6.0), 'green')], dtype=dtype)
print(data)
print(data['position'])
print(data['color'])

[([1., 2.], 'red') ([3., 4.], 'blue') ([5., 6.], 'green')]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
['red' 'blue' 'green']


In [ ]:
#44.How do you compute pairwise distances between coordinates?
coords = np.array([[1, 2], [3, 4], [5, 6]])
diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
distances = np.sqrt(np.sum(diff**2, axis=-1))
print(distances)

[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [ ]:
#45.How do you cast a float array to integer type in place?
import numpy as np
arr = np.array([1.2, 2.8, 3.5], dtype=float)
arr = arr.astype(int, copy=False)
print(arr)
print(arr.dtype)

[1 2 3]
int64


In [ ]:
#46.How do you read data from a file with missing values?
import numpy as np

csv_data = """1,2,3
4,,6
7,8,9"""
with open('data_with_missing.csv', 'w') as f:
    f.write(csv_data)
data = np.genfromtxt('data_with_missing.csv', delimiter=',', filling_values=np.nan)
print(data)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [ ]:
#47.How do you iterate through all elements in a NumPy array with indices?
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 10
Index: (0, 1), Value: 20
Index: (0, 2), Value: 30
Index: (1, 0), Value: 40
Index: (1, 1), Value: 50
Index: (1, 2), Value: 60


In [ ]:
#48.How do you create a 2D Gaussian-like array?
import numpy as np
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
sigma = 0.5
gaussian = np.exp(-(x**2 + y**2) / (2 * sigma**2))
print(gaussian)

[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

In [ ]:
#49.How do you randomly place a specific number of elements in a 2D array?
import numpy as np
arr = np.zeros((5, 5))
num_elements = 5
values = np.arange(1, num_elements + 1)
indices = np.random.choice(arr.size, num_elements, replace=False)
np.put(arr, indices, values)
print(arr)

[[0. 5. 0. 0. 0.]
 [0. 4. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#50.How do you subtract the row mean from a matrix?
import numpy as np
arr = np.zeros((5, 5), dtype=int)
n = 5
indices = np.random.choice(arr.size, n, replace=False)
arr.flat[indices] = 1
print(arr)

[[0 1 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 1]]


Intermediate

In [ ]:
#51.How do you sort a 2D array based on the values of one column?
import numpy as np
arr = np.array([[1, 9, 3],
                [4, 2, 6],
                [7, 5, 0]])
sorted_arr = arr[arr[:, 1].argsort()]
print(sorted_arr)


[[4 2 6]
 [7 5 0]
 [1 9 3]]


In [ ]:
#52.How do you check if a 2D array contains any null (zero-only) columns?
arr = np.array([[0, 1, 0],
                [0, 2, 0],
                [0, 3, 0]])
zero_cols = np.all(arr == 0, axis=0)
print("Zero-only columns:", zero_cols)
print("Contains any zero-only column:", np.any(zero_cols))

Zero-only columns: [ True False  True]
Contains any zero-only column: True


In [ ]:
#53.How do you find the nearest value to a given number in a NumPy array?
arr = np.array([2.5, 7.1, 4.8, 9.6])
value = 5.0
nearest = arr[np.abs(arr - value).argmin()]
print("Nearest value to", value, "is", nearest)

Nearest value to 5.0 is 4.8


In [ ]:
#54.How do you create a NumPy subclass with custom attributes?
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="NoName"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "NoName")
arr = NamedArray(np.arange(5), name="MyArray")
print(arr)
print(arr.name)

[0 1 2 3 4]
MyArray


In [ ]:
#55.How do you increment elements in an array using an index array with repeats?
import numpy as np
arr = np.zeros(5, dtype=int)
indices = np.array([0, 1, 2, 1, 1])
values = np.array([1, 2, 3, 4, 5])
np.add.at(arr, indices, values)
print(arr)

[ 1 11  3  0  0]


In [ ]:
#56.How do you accumulate values into an array based on indices?
values = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 0, 1, 1])
accum = np.bincount(indices, weights=values)
print(accum)

[ 4. 11.]


In [ ]:
#57.How do you count unique colors in a 3D image array?
img = np.random.randint(0, 256, (3, 3, 3), dtype=np.uint8)
pixels = img.reshape(-1, 3)
unique_colors = np.unique(pixels, axis=0)
print("Number of unique colors:", len(unique_colors))

Number of unique colors: 9


In [ ]:
#58.How do you compute the sum across the last two axes of a 4D array?
arr = np.random.rand(2, 3, 4, 5)
result = arr.sum(axis=(-2, -1))
print(result.shape)

(2, 3)


In [ ]:
#59.How do you calculate means of grouped values in an array?
values = np.array([10, 20, 30, 40, 50])
groups = np.array([0, 1, 0, 1, 1])
sum_per_group = np.bincount(groups, weights=values)
count_per_group = np.bincount(groups)
mean_per_group = sum_per_group / count_per_group
print(mean_per_group)

[20.         36.66666667]


In [ ]:
#60.How do you efficiently get the diagonal of a matrix dot product?
A = np.random.rand(3, 5)
B = np.random.rand(3, 5)
diag = np.einsum('ij,ij->i', A, B)
print(diag)

[0.29299305 1.62095065 1.27469153]


In [ ]:
#61.How do you interleave a vector with a fixed number of zeros?
import numpy as np
v = np.array([1, 2, 3])
n_zeros = 2
out = np.zeros(len(v) + (len(v) - 1) * n_zeros, dtype=v.dtype)
out[::n_zeros + 1] = v
print(out)

[1 0 0 2 0 0 3]


In [ ]:
#62.How do you multiply a (5,5,3) array with a (5,5) array element-wise?
a = np.random.rand(5, 5, 3)
b = np.random.rand(5, 5)
result = a * b[:, :, None]
print(result.shape)

(5, 5, 3)


In [ ]:
#63.How do you swap two rows in a matrix?
arr = np.arange(9).reshape(3, 3)
print("Before:\n", arr)
arr[[0, 2]] = arr[[2, 0]]
print("After:\n", arr)


Before:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


In [ ]:
#64.How do you extract unique line segments from triangle definitions?
triangles = np.array([
    [0, 1, 2],
    [2, 3, 0]
])
edges = np.concatenate([
    triangles[:, [0, 1]],
    triangles[:, [1, 2]],
    triangles[:, [2, 0]]
])
edges = np.sort(edges, axis=1)
unique_edges = np.unique(edges, axis=0)
print(unique_edges)

[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [2 3]]


In [ ]:
#65.How do you recreate an array from a bincount?
counts = np.array([2, 0, 3, 1])
reconstructed = np.repeat(np.arange(len(counts)), counts)
print(reconstructed)

[0 0 2 2 2 3]


In [ ]:
#66.How do you compute a moving average using a sliding window?
import numpy as np
a = np.arange(10)
window_size = 3
moving_avg = np.convolve(a, np.ones(window_size)/window_size, mode='valid')
print(moving_avg)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
#67.How do you create a rolling 2D view from a 1D array?
from numpy.lib.stride_tricks import sliding_window_view
a = np.arange(10)
window = 3
view = sliding_window_view(a, window_shape=window)
print(view)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#68.How do you invert booleans or negate floats in-place?
a = np.array([True, False, True])
np.logical_not(a, out=a)   # in-place
print(a)

[False  True False]


In [ ]:
#69.How do you compute the distance from a point to multiple lines?
p0 = np.array([0, 0])
p1 = np.array([[1, 0], [0, 2]])
p2 = np.array([[1, 1], [2, 2]])
line_vec = p2 - p1
point_vec = p1 - p0
cross = np.abs(line_vec[:,0]*point_vec[:,1] - line_vec[:,1]*point_vec[:,0])
dist = cross / np.linalg.norm(line_vec, axis=1)
print(dist)

[1. 2.]


In [ ]:
#70.How do you compute the distances from multiple points to multiple lines?
import numpy as np
p0 = np.array([[0, 0], [1, 1], [2, 1]])
p1 = np.array([[0, 1], [2, 2]])
p2 = np.array([[1, 2], [2, 3]])
v = p2 - p1
w = p1[None, :, :] - p0[:, None, :]
cross = np.abs(v[None,:,0]*w[:,:,1] - v[None,:,1]*w[:,:,0])
dist = cross / np.linalg.norm(v, axis=1)
print(dist)

[[0.70710678 2.        ]
 [0.70710678 1.        ]
 [1.41421356 0.        ]]


In [ ]:
#71.How do you extract a fixed-shaped subarray centered on a given point?
a = np.arange(100).reshape(10, 10)
center = (5, 5)
size = 3
r = size // 2
sub = a[max(center[0]-r, 0): center[0]+r+1,
         max(center[1]-r, 0): center[1]+r+1]
print(sub)

[[44 45 46]
 [54 55 56]
 [64 65 66]]


In [ ]:
#72.How do you generate overlapping subarrays from a vector?
from numpy.lib.stride_tricks import sliding_window_view
a = np.arange(6)
window = 3
windows = sliding_window_view(a, window)
print(windows)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
#73.How do you compute the rank of a matrix using SVD?
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

U, s, Vt = np.linalg.svd(A)
rank = np.sum(s > 1e-10)
print(rank)

2


In [ ]:
#74.How do you find the most frequent value in an array?
a = np.array([1, 2, 2, 3, 3, 3, 4])
values, counts = np.unique(a, return_counts=True)
most_frequent = values[np.argmax(counts)]
print(most_frequent)

3


In [ ]:
#75.How do you extract all 3x3 contiguous blocks from a 10x10 matrix?
a = np.arange(100).reshape(10, 10)
blocks = sliding_window_view(a, (3, 3))
print(blocks.shape)
print(blocks[0, 0])

(8, 8, 3, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [ ]:
#76.How do you create a 2D symmetric matrix class?
import numpy as np

class SymmetricMatrix(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        if not np.allclose(obj, obj.T):
            obj = (obj + obj.T) / 2
        return obj

    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricMatrix, self).__setitem__((i, j), value)
        super(SymmetricMatrix, self).__setitem__((j, i), value)

A = SymmetricMatrix(np.array([[1, 2], [3, 4]]))
print(A)
A[0, 1] = 10
print(A)


[[1.  2.5]
 [2.5 4. ]]
[[ 1. 10.]
 [10.  4.]]


In [ ]:
#77.How do you compute the sum of multiple matrix-vector products at once?
A = np.random.rand(3, 4, 4)
x = np.random.rand(3, 4)
result = np.einsum('ijk,ik->j', A, x)
print(result.shape)

(4,)


In [ ]:
#78.How do you compute the sum of blocks in a 2D array?
A = np.arange(36).reshape(6, 6)
block_size = 2
result = A.reshape(6//block_size, block_size, 6//block_size, block_size).sum(axis=(1, 3))
print(result)

[[ 14  22  30]
 [ 62  70  78]
 [110 118 126]]


In [ ]:
#79.How do you simulate the Game of Life using NumPy?
def game_of_life_step(X):
    N = sum(np.roll(np.roll(X, i, 0), j, 1)
            for i in (-1, 0, 1)
            for j in (-1, 0, 1)
            if (i != 0 or j != 0))
X = np.random.randint(0, 2, (5, 5))
print("Initial:\n", X)
X_next = game_of_life_step(X)
print("Next:\n", X_next)


Initial:
 [[0 1 0 1 1]
 [0 1 0 1 0]
 [1 1 0 0 0]
 [1 0 0 0 1]
 [0 0 1 1 0]]
Next:
 None


In [ ]:
#80.How do you extract the top N largest values from an array?
a = np.array([1, 3, 7, 5, 9, 2])
N = 3
idx = np.argpartition(a, -N)[-N:]
topN = a[idx]
topN_sorted = np.sort(topN)[::-1]
print(topN_sorted)


[9 7 5]


In [ ]:
#81.How do you create a Cartesian product of multiple input arrays?
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
grid = np.array(np.meshgrid(a, b, c)).T.reshape(-1, 3)
print(grid)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


In [ ]:
#82.How do you create a record array from a regular NumPy array?
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
r = np.core.records.fromarrays(arr.T, names='a,b,c')

print(r.a, r.b, r.c)

[1 4] [2 5] [3 6]


/tmp/ipython-input-1252968701.py:4: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  r = np.core.records.fromarrays(arr.T, names='a,b,c')


In [ ]:
#83.How do you raise an array to the power of 3 using different methods?
x = np.arange(5)
print(x ** 3)

[ 0  1  8 27 64]


In [ ]:
#84.How do you find rows in a matrix containing all elements of another matrix?
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 1, 2, 3],
                   [4, 5, 6, 7]])
elements_to_find = np.array([[2, 3],
                             [6, 7]])
contains_all = np.all(np.isin(matrix, elements_to_find), axis=1)
print(contains_all)

[False False False False]


In [ ]:
#85.How do you filter rows in a matrix with at least one differing value?
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 2, 3]])
B = np.array([1, 2, 3])
mask = np.any(A != B, axis=1)
filtered = A[mask]
print(filtered)

[[4 5 6]]


In [ ]:
#86.How do you convert integers to their binary matrix representation?
import numpy as np
nums = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.uint8)
bits = np.unpackbits(nums[:, None], axis=1)
print(bits)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]]


In [ ]:
#87.How do you extract unique rows from a 2D array?
A = np.array([[1, 2, 3],
              [3, 2, 1],
              [1, 2, 3]])
unique_rows = np.unique(A, axis=0)
print(unique_rows)

[[1 2 3]
 [3 2 1]]


In [ ]:
#88.How do you compute inner, outer, sum, and multiplication using einsum?
x = np.arange(3)
y = np.arange(3, 6)
inner = np.einsum('i,i->', x, y)
outer = np.einsum('i,j->ij', x, y)
summed = np.einsum('i,i->i', x, y) + x
product = np.einsum('i,i->i', x, y)
print(inner, "\n", outer, "\n", product)


14 
 [[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]] 
 [ 0  4 10]


In [ ]:
#89.How do you sample a 2D path at regular intervals?
points = np.array([[0, 0], [1, 2], [4, 3], [7, 3]])
dist = np.cumsum(np.sqrt(np.sum(np.diff(points, axis=0)**2, axis=1)))
dist = np.insert(dist, 0, 0)
intervals = np.linspace(0, dist[-1], 10)
x = np.interp(intervals, dist, points[:, 0])
y = np.interp(intervals, dist, points[:, 1])
sampled = np.stack([x, y], axis=1)
print(sampled)


[[0.         0.        ]
 [0.41731715 0.8346343 ]
 [0.8346343  1.6692686 ]
 [1.53446974 2.17815658]
 [2.4197331  2.47324437]
 [3.30499646 2.76833215]
 [4.20055145 3.        ]
 [5.13370097 3.        ]
 [6.06685048 3.        ]
 [7.         3.        ]]


In [ ]:
#90.How do you filter 2D array rows that sum to a specific number using only integers?
A = np.array([[1, 2, 3],
              [3, 3, 3],
              [2, 2, 4],
              [0, 5, 1]])
target = 6
filtered = A[np.sum(A, axis=1) == target]
print(filtered)

[[1 2 3]
 [0 5 1]]


Additional Practice (Bonus: 91–110)

In [ ]:
#91.How do you vertically and horizontally stack two arrays?
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
vstacked = np.vstack((A, B))
print("Vertical stack:\n", vstacked)
hstacked = np.hstack((A, B))
print("Horizontal stack:\n", hstacked)


Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#92.How do you apply a custom function to each element of an array?
def my_func(x):
    return x**2 + 1
arr = np.array([1, 2, 3, 4])
vec_func = np.vectorize(my_func)
result = vec_func(arr)
print(result)

[ 2  5 10 17]


In [ ]:
#93.How do you remove duplicate rows in a 2D array?
A = np.array([[1, 2],
              [3, 4],
              [1, 2]])
unique_rows = np.unique(A, axis=0)
print(unique_rows)


[[1 2]
 [3 4]]


In [ ]:
#94.How do you filter rows based on a specific column value?
A = np.array([[1, 2],
              [3, 4],
              [5, 2]])
filtered = A[A[:, 1] == 2]
print(filtered)


[[1 2]
 [5 2]]


In [ ]:
#95.How do you find column-wise and row-wise minimum/maximum indices?
import numpy as np
A = np.array([[3, 1, 4],
              [2, 5, 0],
              [7, 2, 6]])
col_min_idx = np.argmin(A, axis=0)
col_max_idx = np.argmax(A, axis=0)
row_min_idx = np.argmin(A, axis=1)
row_max_idx = np.argmax(A, axis=1)

print("Col min indices:", col_min_idx)
print("Col max indices:", col_max_idx)
print("Row min indices:", row_min_idx)
print("Row max indices:", row_max_idx)


Col min indices: [1 0 1]
Col max indices: [2 1 2]
Row min indices: [1 2 1]
Row max indices: [2 1 0]


In [ ]:
#96.How do you replace NaN values in an array with the column mean?
A = np.array([[1, 2, np.nan],
              [4, np.nan, 6],
              [7, 8, 9]], dtype=float)
col_mean = np.nanmean(A, axis=0)
inds = np.where(np.isnan(A))
A[inds] = np.take(col_mean, inds[1])
print(A)


[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [ ]:
#97.How do you flatten and sort a 2D array?
A = np.array([[3, 1, 4],
              [2, 5, 0]])

flattened_sorted = np.sort(A.ravel())
print(flattened_sorted)

[0 1 2 3 4 5]


In [ ]:
#98.How do you calculate the correlation coefficient between two vectors?
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

corr = np.corrcoef(x, y)[0, 1]
print(corr)


1.0


In [ ]:
#99.How do you extract the top-K values along a specific axis?
A = np.array([[1, 3, 2],
              [7, 5, 6]])
K = 2
idx = np.argpartition(-A, K-1, axis=1)[:, :K]
topK = np.take_along_axis(A, idx, axis=1)
print(topK)

[[3 2]
 [7 6]]


In [ ]:
#100.How do you detect outliers in a dataset using IQR?
import numpy as np
A = np.array([1, 2, 5, 7, 10, 12, 15, 100])
Q1 = np.percentile(A, 25)
Q3 = np.percentile(A, 75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = A[(A < lower_bound) | (A > upper_bound)]

print("Data:", A)
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Outliers:", outliers)

Data: [  1   2   5   7  10  12  15 100]
Q1: 4.25
Q3: 12.75
IQR: 8.5
Lower bound: -8.5
Upper bound: 25.5
Outliers: [100]


In [ ]:
#101.How do you perform one-hot encoding using NumPy?
import numpy as np
labels = np.array([0, 2, 1, 3])
num_classes = 4
one_hot = np.zeros((labels.size, num_classes), dtype=int)
one_hot[np.arange(labels.size), labels] = 1
print(one_hot)


[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [ ]:
#102.How do you find the shape and number of elements in an array?
A = np.random.rand(3, 4, 5)
print("Shape:", A.shape)
print("Number of elements:", A.size)


Shape: (3, 4, 5)
Number of elements: 60


In [ ]:
#103.How do you reshape an array without changing its data?
A = np.arange(12)
B = A.reshape(3, 4)
print(B)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#104.How do you flatten a multi-dimensional array?
A = np.array([[1, 2, 3],
              [4, 5, 6]])

flat1 = A.ravel()
flat2 = A.flatten()

print(flat1)
print(flat2)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#105.How do you get the cumulative sum along an axis?
A = np.array([[1, 2, 3],
              [4, 5, 6]])

cumsum0 = np.cumsum(A, axis=0)

cumsum1 = np.cumsum(A, axis=1)

print("Axis 0:\n", cumsum0)
print("Axis 1:\n", cumsum1)


Axis 0:
 [[1 2 3]
 [5 7 9]]
Axis 1:
 [[ 1  3  6]
 [ 4  9 15]]


In [ ]:
#106.How do you compute element-wise maximum/minimum of two arrays?
import numpy as np

A = np.array([1, 4, 3])
B = np.array([2, 2, 5])

elem_max = np.maximum(A, B)
elem_min = np.minimum(A, B)

print("Element-wise max:", elem_max)
print("Element-wise min:", elem_min)


Element-wise max: [2 4 5]
Element-wise min: [1 2 3]


In [ ]:
#107.How do you broadcast arrays with different shapes?
A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30])
C = A + B
print(C)
print("Shape:", C.shape)


[[11 21 31]
 [12 22 32]
 [13 23 33]]
Shape: (3, 3)


In [ ]:
#108.How do you transpose a matrix and perform dot products?
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

At = A.T

dot_AB = np.dot(A, B)
dot_AtB = np.dot(At, B)

print("A.T:\n", At)
print("A·B:\n", dot_AB)
print("A.T·B:\n", dot_AtB)


A.T:
 [[1 3]
 [2 4]]
A·B:
 [[19 22]
 [43 50]]
A.T·B:
 [[26 30]
 [38 44]]


In [ ]:
#109.How do you check for NaN or infinite values in an array?
A = np.array([1, np.nan, np.inf, -np.inf, 5])

nan_mask = np.isnan(A)
inf_mask = np.isinf(A)
finite_mask = np.isfinite(A)

print("NaNs:", nan_mask)
print("Infs:", inf_mask)
print("Finite:", finite_mask)


NaNs: [False  True False False False]
Infs: [False False  True  True False]
Finite: [ True False False False  True]


In [ ]:
#110.How do you extract diagonal, upper, and lower triangles from a matrix?
A = np.arange(1, 10).reshape(3, 3)

diag = np.diag(A)
upper = np.triu(A)
lower = np.tril(A)

print("Diagonal:", diag)
print("Upper triangle:\n", upper)
print("Lower triangle:\n", lower)


Diagonal: [1 5 9]
Upper triangle:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower triangle:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
